version: '3.8'

services:
  # Tvoj sistem
  preschool-app:
    build: ./preschool-service
    ports:
      - "8081:8081"
    container_name: preschool-service

  # Kolegin sistem
  analytics-app:
    build: ./analytics-service
    ports:
      - "8082:8082"
    container_name: analytics-service

  # SSO Sistem (Zajedniƒçki - Keycloak)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"